"""Jinja2 rendering for qr_v2 candidate artifacts."""

import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, StrictUndefined

from gpumode.qr_v2.jsonl import write_jsonl
from gpumode.qr_v2.specs import QrV2Spec


RENDERER_VERSION = "render_v1"


@dataclass(frozen=True, slots=True)
class QrV2KernelConfig:
    candidate_id: str
    template_id: str
    threads_per_block: int
    tile_size: int
    unroll: int

    @property
    def entry_point(self) -> str:
        return f"{self.candidate_id}_kernel"


SERIAL_KERNEL_CONFIG = QrV2KernelConfig(
    candidate_id="qr_v2_geqr2_serial_tpb128_tile32",
    template_id="cuda_geqr2_serial_v1",
    threads_per_block=128,
    tile_size=32,
    unroll=1,
)

PARALLEL_KERNEL_CONFIG = QrV2KernelConfig(
    candidate_id="qr_v2_geqr2_parallel_tpb256_tile32",
    template_id="cuda_geqr2_parallel_v1",
    threads_per_block=256,
    tile_size=32,
    unroll=1,
)

KERNEL_CONFIGS: dict[str, QrV2KernelConfig] = {
    "serial": SERIAL_KERNEL_CONFIG,
    "parallel": PARALLEL_KERNEL_CONFIG,
}
DEFAULT_KERNEL_CONFIG = SERIAL_KERNEL_CONFIG


@dataclass(frozen=True, slots=True)
class RenderSuiteResult:
    manifest_path: Path
    records: list[dict[str, object]]

    @property
    def artifact_paths(self) -> list[Path]:
        return [Path(str(record["artifact_path"])) for record in self.records]


@dataclass(frozen=True, slots=True)
class RenderVerificationIssue:
    code: str
    message: str
    artifact_path: str | None = None
    line_number: int | None = None

    def to_record(self) -> dict[str, object]:
        record: dict[str, object] = {
            "code": self.code,
            "message": self.message,
        }
        if self.artifact_path is not None:
            record["artifact_path"] = self.artifact_path
        if self.line_number is not None:
            record["line_number"] = self.line_number
        return record


@dataclass(frozen=True, slots=True)
class RenderVerificationResult:
    manifest_path: Path
    records_checked: int
    artifacts_checked: int
    issues: list[RenderVerificationIssue]

    @property
    def ok(self) -> bool:
        return not self.issues


_CUDA_GEQR2_SERIAL_TEMPLATE = """// Generated by gpumode.qr_v2 {{ renderer_version }}.
// Correct-first serial GEQR2 implementation for validating qr_v2 plumbing.
//
// candidate_id: {{ config.candidate_id }}
// template_id: {{ config.template_id }}
// entry_point: {{ config.entry_point }}
// eval: {{ spec.eval_line(include_dense_case=True) }}
// shape: batch={{ spec.batch }}, n={{ spec.n }}, cond={{ spec.cond }}, case={{ spec.case }}, seed={{ spec.seed }}
// sweep: threads_per_block={{ config.threads_per_block }}, tile_size={{ config.tile_size }}, unroll={{ config.unroll }}

#include <cuda_runtime.h>
#include <math.h>

extern "C" __global__ void {{ config.entry_point }}(
    const float* __restrict__ a,
    float* __restrict__ h,
    float* __restrict__ tau,
    int batch,
    int n
) {
    const int matrix_idx = blockIdx.x;
    if (matrix_idx >= batch || threadIdx.x != 0) {
        return;
    }

    const int matrix_offset = matrix_idx * n * n;
    const int tau_offset = matrix_idx * n;

    for (int idx = 0; idx < n * n; ++idx) {
        h[matrix_offset + idx] = a[matrix_offset + idx];
    }
    for (int k = 0; k < n; ++k) {
        tau[tau_offset + k] = 0.0f;
    }

    for (int k = 0; k < n; ++k) {
        const int kk = matrix_offset + k * n + k;
        const double alpha = static_cast<double>(h[kk]);
        double xnorm2 = 0.0;

        for (int row = k + 1; row < n; ++row) {
            const double value = static_cast<double>(h[matrix_offset + row * n + k]);
            xnorm2 += value * value;
        }
        if (xnorm2 == 0.0) {
            tau[tau_offset + k] = 0.0f;
            continue;
        }

        const double norm = sqrt(alpha * alpha + xnorm2);
        const double beta = alpha >= 0.0 ? -norm : norm;
        const double tau_k = (beta - alpha) / beta;
        const double scale = 1.0 / (alpha - beta);

        for (int row = k + 1; row < n; ++row) {
            const int index = matrix_offset + row * n + k;
            h[index] = static_cast<float>(static_cast<double>(h[index]) * scale);
        }
        h[kk] = static_cast<float>(beta);
        tau[tau_offset + k] = static_cast<float>(tau_k);

        for (int col = k + 1; col < n; ++col) {
            double dot = static_cast<double>(h[matrix_offset + k * n + col]);
            for (int row = k + 1; row < n; ++row) {
                dot += static_cast<double>(h[matrix_offset + row * n + k]) *
                       static_cast<double>(h[matrix_offset + row * n + col]);
            }

            const double update = tau_k * dot;
            const int top_index = matrix_offset + k * n + col;
            h[top_index] = static_cast<float>(static_cast<double>(h[top_index]) - update);
            for (int row = k + 1; row < n; ++row) {
                const int index = matrix_offset + row * n + col;
                h[index] = static_cast<float>(
                    static_cast<double>(h[index]) - static_cast<double>(h[matrix_offset + row * n + k]) * update
                );
            }
        }
    }
}

extern "C" __attribute__((visibility("default"))) int {{ config.entry_point }}_launch(
    const float* a,
    float* h,
    float* tau,
    int batch,
    int n,
    int threads_per_block
) {
    if (a == nullptr || h == nullptr || tau == nullptr || batch <= 0 || n <= 0 || threads_per_block <= 0) {
        return -1;
    }

    {{ config.entry_point }}<<<batch, threads_per_block>>>(a, h, tau, batch, n);
    cudaError_t launch_status = cudaGetLastError();
    if (launch_status != cudaSuccess) {
        return static_cast<int>(launch_status);
    }

    cudaError_t sync_status = cudaDeviceSynchronize();
    if (sync_status != cudaSuccess) {
        return static_cast<int>(sync_status);
    }
    return 0;
}
"""


_CUDA_GEQR2_PARALLEL_TEMPLATE = """// Generated by gpumode.qr_v2 {{ renderer_version }}.
// Correct-first cooperative GEQR2 implementation with block reductions.
//
// candidate_id: {{ config.candidate_id }}
// template_id: {{ config.template_id }}
// entry_point: {{ config.entry_point }}
// eval: {{ spec.eval_line(include_dense_case=True) }}
// shape: batch={{ spec.batch }}, n={{ spec.n }}, cond={{ spec.cond }}, case={{ spec.case }}, seed={{ spec.seed }}
// sweep: threads_per_block={{ config.threads_per_block }}, tile_size={{ config.tile_size }}, unroll={{ config.unroll }}

#include <cuda_runtime.h>
#include <math.h>

extern "C" __global__ void {{ config.entry_point }}(
    const float* __restrict__ a,
    float* __restrict__ h,
    float* __restrict__ tau,
    int batch,
    int n
) {
    const int matrix_idx = blockIdx.x;
    const int tid = threadIdx.x;
    if (matrix_idx >= batch) {
        return;
    }

    __shared__ double reduce_buffer[1024];
    __shared__ double shared_tau;
    __shared__ double shared_scale;
    __shared__ double shared_update;
    __shared__ int shared_active;

    const int matrix_offset = matrix_idx * n * n;
    const int tau_offset = matrix_idx * n;

    for (int idx = tid; idx < n * n; idx += blockDim.x) {
        h[matrix_offset + idx] = a[matrix_offset + idx];
    }
    for (int k = tid; k < n; k += blockDim.x) {
        tau[tau_offset + k] = 0.0f;
    }
    __syncthreads();

    for (int k = 0; k < n; ++k) {
        double local_sum = 0.0;
        for (int row = k + 1 + tid; row < n; row += blockDim.x) {
            const double value = static_cast<double>(h[matrix_offset + row * n + k]);
            local_sum += value * value;
        }
        reduce_buffer[tid] = local_sum;
        __syncthreads();

        for (int stride = blockDim.x >> 1; stride > 0; stride >>= 1) {
            if (tid < stride) {
                reduce_buffer[tid] += reduce_buffer[tid + stride];
            }
            __syncthreads();
        }

        if (tid == 0) {
            const int kk = matrix_offset + k * n + k;
            const double alpha = static_cast<double>(h[kk]);
            const double xnorm2 = reduce_buffer[0];
            if (xnorm2 == 0.0) {
                tau[tau_offset + k] = 0.0f;
                shared_tau = 0.0;
                shared_scale = 0.0;
                shared_active = 0;
            } else {
                const double norm = sqrt(alpha * alpha + xnorm2);
                const double beta = alpha >= 0.0 ? -norm : norm;
                const double tau_k = (beta - alpha) / beta;
                shared_tau = tau_k;
                shared_scale = 1.0 / (alpha - beta);
                shared_active = 1;
                h[kk] = static_cast<float>(beta);
                tau[tau_offset + k] = static_cast<float>(tau_k);
            }
        }
        __syncthreads();

        if (shared_active == 0) {
            continue;
        }

        for (int row = k + 1 + tid; row < n; row += blockDim.x) {
            const int index = matrix_offset + row * n + k;
            h[index] = static_cast<float>(static_cast<double>(h[index]) * shared_scale);
        }
        __syncthreads();

        for (int col = k + 1; col < n; ++col) {
            double dot = tid == 0 ? static_cast<double>(h[matrix_offset + k * n + col]) : 0.0;
            for (int row = k + 1 + tid; row < n; row += blockDim.x) {
                dot += static_cast<double>(h[matrix_offset + row * n + k]) *
                       static_cast<double>(h[matrix_offset + row * n + col]);
            }
            reduce_buffer[tid] = dot;
            __syncthreads();

            for (int stride = blockDim.x >> 1; stride > 0; stride >>= 1) {
                if (tid < stride) {
                    reduce_buffer[tid] += reduce_buffer[tid + stride];
                }
                __syncthreads();
            }

            if (tid == 0) {
                shared_update = shared_tau * reduce_buffer[0];
                const int top_index = matrix_offset + k * n + col;
                h[top_index] = static_cast<float>(static_cast<double>(h[top_index]) - shared_update);
            }
            __syncthreads();

            for (int row = k + 1 + tid; row < n; row += blockDim.x) {
                const int index = matrix_offset + row * n + col;
                h[index] = static_cast<float>(
                    static_cast<double>(h[index]) - static_cast<double>(h[matrix_offset + row * n + k]) * shared_update
                );
            }
            __syncthreads();
        }
    }
}

extern "C" __attribute__((visibility("default"))) int {{ config.entry_point }}_launch(
    const float* a,
    float* h,
    float* tau,
    int batch,
    int n,
    int threads_per_block
) {
    if (a == nullptr || h == nullptr || tau == nullptr || batch <= 0 || n <= 0 || threads_per_block <= 0) {
        return -1;
    }
    if (threads_per_block > 1024 || (threads_per_block & (threads_per_block - 1)) != 0) {
        return -2;
    }

    {{ config.entry_point }}<<<batch, threads_per_block>>>(a, h, tau, batch, n);
    cudaError_t launch_status = cudaGetLastError();
    if (launch_status != cudaSuccess) {
        return static_cast<int>(launch_status);
    }

    cudaError_t sync_status = cudaDeviceSynchronize();
    if (sync_status != cudaSuccess) {
        return static_cast<int>(sync_status);
    }
    return 0;
}
"""

_CUDA_TEMPLATES = {
    "cuda_geqr2_serial_v1": _CUDA_GEQR2_SERIAL_TEMPLATE,
    "cuda_geqr2_parallel_v1": _CUDA_GEQR2_PARALLEL_TEMPLATE,
}

_JINJA_ENV = Environment(
    autoescape=False,
    lstrip_blocks=True,
    trim_blocks=True,
    undefined=StrictUndefined,
)


def _artifact_stem(spec: QrV2Spec, index: int) -> str:
    return f"{index:04d}_{spec.case}_b{spec.batch}_n{spec.n}_c{spec.cond}_seed{spec.seed}"


def _render_source(spec: QrV2Spec, config: QrV2KernelConfig) -> str:
    template = _JINJA_ENV.from_string(_CUDA_TEMPLATES[config.template_id])
    return template.render(
        config=config,
        renderer_version=RENDERER_VERSION,
        spec=spec,
    )


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def render_suite(
    *,
    suite: str,
    specs: list[QrV2Spec],
    out_dir: Path,
    config: QrV2KernelConfig = DEFAULT_KERNEL_CONFIG,
) -> RenderSuiteResult:
    artifact_dir = out_dir / config.candidate_id
    artifact_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, object]] = []
    for index, spec in enumerate(specs):
        source = _render_source(spec, config)
        artifact_path = artifact_dir / f"{_artifact_stem(spec, index)}.cu"
        artifact_path.write_text(source, encoding="utf-8")
        records.append(
            {
                "event": "render_result",
                "renderer_version": RENDERER_VERSION,
                "suite": suite,
                "artifact_kind": config.template_id,
                "artifact_path": artifact_path.as_posix(),
                "artifact_bytes": len(source.encode("utf-8")),
                "artifact_sha256": _sha256_text(source),
                "entry_point": config.entry_point,
                **asdict(config),
                **spec.kwargs(),
            }
        )

    manifest_path = out_dir / "manifest.jsonl"
    write_jsonl(manifest_path, records)
    return RenderSuiteResult(manifest_path=manifest_path, records=records)


def _load_manifest_records(manifest_path: Path) -> tuple[list[dict[str, Any]], list[RenderVerificationIssue]]:
    if not manifest_path.exists():
        return [], [RenderVerificationIssue(code="missing_manifest", message=f"missing manifest: {manifest_path}")]

    records: list[dict[str, Any]] = []
    issues: list[RenderVerificationIssue] = []
    with manifest_path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                parsed = json.loads(stripped)
            except json.JSONDecodeError as error:
                issues.append(
                    RenderVerificationIssue(
                        code="invalid_json",
                        message=f"invalid JSON: {error.msg}",
                        line_number=line_number,
                    )
                )
                continue
            if not isinstance(parsed, dict):
                issues.append(
                    RenderVerificationIssue(
                        code="invalid_record",
                        message="manifest row is not a JSON object",
                        line_number=line_number,
                    )
                )
                continue
            parsed["_line_number"] = line_number
            records.append(parsed)
    return records, issues


def _string_field(
    record: dict[str, Any],
    field: str,
    issues: list[RenderVerificationIssue],
) -> str | None:
    value = record.get(field)
    if isinstance(value, str) and value:
        return value
    issues.append(
        RenderVerificationIssue(
            code=f"invalid_{field}",
            message=f"missing or invalid {field!r}",
            line_number=int(record["_line_number"]),
        )
    )
    return None


def _int_field(
    record: dict[str, Any],
    field: str,
    issues: list[RenderVerificationIssue],
    *,
    artifact_path: str | None = None,
) -> int | None:
    value = record.get(field)
    if isinstance(value, int):
        return value
    issues.append(
        RenderVerificationIssue(
            code=f"invalid_{field}",
            message=f"missing or invalid {field!r}",
            artifact_path=artifact_path,
            line_number=int(record["_line_number"]),
        )
    )
    return None


def verify_render_manifest(manifest_path: Path) -> RenderVerificationResult:
    records, issues = _load_manifest_records(manifest_path)
    seen_paths: set[str] = set()
    artifacts_checked = 0

    for record in records:
        line_number = int(record["_line_number"])
        if record.get("event") != "render_result":
            issues.append(
                RenderVerificationIssue(
                    code="invalid_event",
                    message="manifest row event is not 'render_result'",
                    line_number=line_number,
                )
            )

        artifact_path = _string_field(record, "artifact_path", issues)
        expected_sha256 = _string_field(record, "artifact_sha256", issues)
        expected_bytes = _int_field(record, "artifact_bytes", issues, artifact_path=artifact_path)
        if artifact_path is None:
            continue

        if artifact_path in seen_paths:
            issues.append(
                RenderVerificationIssue(
                    code="duplicate_artifact_path",
                    message="duplicate artifact path in manifest",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
        seen_paths.add(artifact_path)

        path = Path(artifact_path)
        if path.is_absolute():
            issues.append(
                RenderVerificationIssue(
                    code="absolute_artifact_path",
                    message="artifact path must be relative",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
            continue
        if path.parts[:1] != ("data",):
            issues.append(
                RenderVerificationIssue(
                    code="artifact_path_outside_data",
                    message="artifact path must stay under ./data/",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
            continue
        if not path.exists():
            issues.append(
                RenderVerificationIssue(
                    code="missing_artifact",
                    message="artifact path does not exist",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
            continue

        content = path.read_bytes()
        artifacts_checked += 1
        actual_bytes = len(content)
        if expected_bytes is not None and actual_bytes != expected_bytes:
            issues.append(
                RenderVerificationIssue(
                    code="artifact_bytes_mismatch",
                    message=f"expected {expected_bytes} bytes, found {actual_bytes}",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )

        actual_sha256 = _sha256_bytes(content)
        if expected_sha256 is not None and actual_sha256 != expected_sha256:
            issues.append(
                RenderVerificationIssue(
                    code="artifact_sha256_mismatch",
                    message=f"expected {expected_sha256}, found {actual_sha256}",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )

    return RenderVerificationResult(
        manifest_path=manifest_path,
        records_checked=len(records),
        artifacts_checked=artifacts_checked,
        issues=issues,
    )
