"""Jinja2 rendering for qr_v2 candidate artifacts."""

import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, StrictUndefined

from gpumode.qr_v2.jsonl import write_jsonl
from gpumode.qr_v2.specs import QrV2Spec


RENDERER_VERSION = "render_v1"


@dataclass(frozen=True, slots=True)
class QrV2KernelConfig:
    candidate_id: str
    template_id: str
    threads_per_block: int
    tile_size: int
    unroll: int

    @property
    def entry_point(self) -> str:
        return f"{self.candidate_id}_kernel"


DEFAULT_KERNEL_CONFIG = QrV2KernelConfig(
    candidate_id="qr_v2_stub_tpb128_tile32",
    template_id="cuda_stub_v0",
    threads_per_block=128,
    tile_size=32,
    unroll=1,
)


@dataclass(frozen=True, slots=True)
class RenderSuiteResult:
    manifest_path: Path
    records: list[dict[str, object]]

    @property
    def artifact_paths(self) -> list[Path]:
        return [Path(str(record["artifact_path"])) for record in self.records]


@dataclass(frozen=True, slots=True)
class RenderVerificationIssue:
    code: str
    message: str
    artifact_path: str | None = None
    line_number: int | None = None

    def to_record(self) -> dict[str, object]:
        record: dict[str, object] = {
            "code": self.code,
            "message": self.message,
        }
        if self.artifact_path is not None:
            record["artifact_path"] = self.artifact_path
        if self.line_number is not None:
            record["line_number"] = self.line_number
        return record


@dataclass(frozen=True, slots=True)
class RenderVerificationResult:
    manifest_path: Path
    records_checked: int
    artifacts_checked: int
    issues: list[RenderVerificationIssue]

    @property
    def ok(self) -> bool:
        return not self.issues


_CUDA_STUB_TEMPLATE = """// Generated by gpumode.qr_v2 {{ renderer_version }}.
// This is a deterministic render-path smoke artifact, not a correct QR kernel.
//
// candidate_id: {{ config.candidate_id }}
// template_id: {{ config.template_id }}
// entry_point: {{ config.entry_point }}
// eval: {{ spec.eval_line(include_dense_case=True) }}
// shape: batch={{ spec.batch }}, n={{ spec.n }}, cond={{ spec.cond }}, case={{ spec.case }}, seed={{ spec.seed }}
// sweep: threads_per_block={{ config.threads_per_block }}, tile_size={{ config.tile_size }}, unroll={{ config.unroll }}

#include <cuda_runtime.h>

extern "C" __global__ void {{ config.entry_point }}(
    const float* __restrict__ a,
    float* __restrict__ h,
    float* __restrict__ tau,
    int batch,
    int n
) {
    // Placeholder only: the L4 implementation will replace this body.
    // Keeping the signature stable lets manifests, launch wiring, and summaries settle first.
    const int matrix_idx = blockIdx.x;
    const int lane = threadIdx.x;
    if (matrix_idx >= batch || lane >= n) {
        return;
    }

    const int offset = matrix_idx * n * n;
    h[offset + lane * n + lane] = a[offset + lane * n + lane];
    if (lane == 0) {
        tau[matrix_idx * n] = 0.0f;
    }
}
"""

_JINJA_ENV = Environment(
    autoescape=False,
    lstrip_blocks=True,
    trim_blocks=True,
    undefined=StrictUndefined,
)


def _artifact_stem(spec: QrV2Spec, index: int) -> str:
    return f"{index:04d}_{spec.case}_b{spec.batch}_n{spec.n}_c{spec.cond}_seed{spec.seed}"


def _render_source(spec: QrV2Spec, config: QrV2KernelConfig) -> str:
    template = _JINJA_ENV.from_string(_CUDA_STUB_TEMPLATE)
    return template.render(
        config=config,
        renderer_version=RENDERER_VERSION,
        spec=spec,
    )


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def render_suite(
    *,
    suite: str,
    specs: list[QrV2Spec],
    out_dir: Path,
    config: QrV2KernelConfig = DEFAULT_KERNEL_CONFIG,
) -> RenderSuiteResult:
    artifact_dir = out_dir / config.candidate_id
    artifact_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, object]] = []
    for index, spec in enumerate(specs):
        source = _render_source(spec, config)
        artifact_path = artifact_dir / f"{_artifact_stem(spec, index)}.cu"
        artifact_path.write_text(source, encoding="utf-8")
        records.append(
            {
                "event": "render_result",
                "renderer_version": RENDERER_VERSION,
                "suite": suite,
                "artifact_kind": "cuda_stub",
                "artifact_path": artifact_path.as_posix(),
                "artifact_bytes": len(source.encode("utf-8")),
                "artifact_sha256": _sha256_text(source),
                "entry_point": config.entry_point,
                **asdict(config),
                **spec.kwargs(),
            }
        )

    manifest_path = out_dir / "manifest.jsonl"
    write_jsonl(manifest_path, records)
    return RenderSuiteResult(manifest_path=manifest_path, records=records)


def _load_manifest_records(manifest_path: Path) -> tuple[list[dict[str, Any]], list[RenderVerificationIssue]]:
    if not manifest_path.exists():
        return [], [RenderVerificationIssue(code="missing_manifest", message=f"missing manifest: {manifest_path}")]

    records: list[dict[str, Any]] = []
    issues: list[RenderVerificationIssue] = []
    with manifest_path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                parsed = json.loads(stripped)
            except json.JSONDecodeError as error:
                issues.append(
                    RenderVerificationIssue(
                        code="invalid_json",
                        message=f"invalid JSON: {error.msg}",
                        line_number=line_number,
                    )
                )
                continue
            if not isinstance(parsed, dict):
                issues.append(
                    RenderVerificationIssue(
                        code="invalid_record",
                        message="manifest row is not a JSON object",
                        line_number=line_number,
                    )
                )
                continue
            parsed["_line_number"] = line_number
            records.append(parsed)
    return records, issues


def _string_field(
    record: dict[str, Any],
    field: str,
    issues: list[RenderVerificationIssue],
) -> str | None:
    value = record.get(field)
    if isinstance(value, str) and value:
        return value
    issues.append(
        RenderVerificationIssue(
            code=f"invalid_{field}",
            message=f"missing or invalid {field!r}",
            line_number=int(record["_line_number"]),
        )
    )
    return None


def _int_field(
    record: dict[str, Any],
    field: str,
    issues: list[RenderVerificationIssue],
    *,
    artifact_path: str | None = None,
) -> int | None:
    value = record.get(field)
    if isinstance(value, int):
        return value
    issues.append(
        RenderVerificationIssue(
            code=f"invalid_{field}",
            message=f"missing or invalid {field!r}",
            artifact_path=artifact_path,
            line_number=int(record["_line_number"]),
        )
    )
    return None


def verify_render_manifest(manifest_path: Path) -> RenderVerificationResult:
    records, issues = _load_manifest_records(manifest_path)
    seen_paths: set[str] = set()
    artifacts_checked = 0

    for record in records:
        line_number = int(record["_line_number"])
        if record.get("event") != "render_result":
            issues.append(
                RenderVerificationIssue(
                    code="invalid_event",
                    message="manifest row event is not 'render_result'",
                    line_number=line_number,
                )
            )

        artifact_path = _string_field(record, "artifact_path", issues)
        expected_sha256 = _string_field(record, "artifact_sha256", issues)
        expected_bytes = _int_field(record, "artifact_bytes", issues, artifact_path=artifact_path)
        if artifact_path is None:
            continue

        if artifact_path in seen_paths:
            issues.append(
                RenderVerificationIssue(
                    code="duplicate_artifact_path",
                    message="duplicate artifact path in manifest",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
        seen_paths.add(artifact_path)

        path = Path(artifact_path)
        if path.is_absolute():
            issues.append(
                RenderVerificationIssue(
                    code="absolute_artifact_path",
                    message="artifact path must be relative",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
            continue
        if path.parts[:1] != ("data",):
            issues.append(
                RenderVerificationIssue(
                    code="artifact_path_outside_data",
                    message="artifact path must stay under ./data/",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
            continue
        if not path.exists():
            issues.append(
                RenderVerificationIssue(
                    code="missing_artifact",
                    message="artifact path does not exist",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )
            continue

        content = path.read_bytes()
        artifacts_checked += 1
        actual_bytes = len(content)
        if expected_bytes is not None and actual_bytes != expected_bytes:
            issues.append(
                RenderVerificationIssue(
                    code="artifact_bytes_mismatch",
                    message=f"expected {expected_bytes} bytes, found {actual_bytes}",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )

        actual_sha256 = _sha256_bytes(content)
        if expected_sha256 is not None and actual_sha256 != expected_sha256:
            issues.append(
                RenderVerificationIssue(
                    code="artifact_sha256_mismatch",
                    message=f"expected {expected_sha256}, found {actual_sha256}",
                    artifact_path=artifact_path,
                    line_number=line_number,
                )
            )

    return RenderVerificationResult(
        manifest_path=manifest_path,
        records_checked=len(records),
        artifacts_checked=artifacts_checked,
        issues=issues,
    )
